### ISSUE TITLE
Relative exclude paths?

### ISSUE THREAD

**Issue by tnrich** [henvic/ToggleExclude#1]
Is it possible to exclude folders/files by paths relative to the project root?

Thanks for the awesome tool!

**Comment by tnrich** [comment]
Whoops scratch this request. It is totally possible to exclude using paths relative to the project root! 

I was just including the project root folder by accident so nothing was being found. 

Thanks again!

**Comment by henvic** [comment]
Thanks! Glad to hear someone besides me is using it!

**Comment by tnrich** [comment]
It is great!
